Add link in docs landing page to Elastic Stack components overview
elastic/docs pull request #2547
Opened 2022-10-18 17:50 UTC by kilfoyle

~~ Please don't merge until after https://github.com/elastic/tech-content/pull/240 has merged. ~~

This adds a link on the [docs landing page](https://www.elastic.co/guide/index.html), pointing to the new `An overview of the Elastic Stack` page, soon to come via https://github.com/elastic/tech-content/pull/240

@abdon and I aren't sure exactly where this link should go. It may not really belong in the "Featured topics" section of the landing page, but the "Getting started" section is really for all the hands-on guides, so neither place seems ideal. Any suggestions are most welcome!

Rel: https://github.com/elastic/tech-content/issues/229

2022-10-19 13:36 UTC, nrichers requested changes
Thank you for this PR to add a link to the component overview from the front page of our docs! I don't know what the right answer is, but I think we want to tweak the location of this link a bit. The "Add your data" topic is white hot in the CrazyEgg heatmap and we likely do not want to put a conceptual overview above the task of adding data. 

<img width="625" alt="image" src="https://user-images.githubusercontent.com/15148011/196705344-3748dc35-011b-46ca-b9ee-5f40ab7df2b6.png">

One option might be to add it to the bottom of the content inside of the twistie, e.g. somewhere like this, maybe? Or somewhere within this section of text, so that the link is available to folks who have expanded the twistie to indicate they want to learn more about the bits that make up the stack. 

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/15148011/196706155-5b2deb66-9a35-4136-a198-a034588c12fb.png">

2022-10-19 14:05 UTC, abdonpijpelink commented
Considering the information on the new page is largely the same as the "About the Elastic Stack" section, maybe we can simply replace that section with a link to the new page? For example a link "Learn more about the Elastic Stack" as the end of the first sentence "Elastic provides..."?

2022-10-20 18:00 UTC, KOTungseth commented
> Considering the information on the new page is largely the same as the "About the Elastic Stack" section, maybe we can simply replace that section with a link to the new page? For example a link "Learn more about the Elastic Stack" at the end of the first sentence "Elastic provides..."?

I agree that the information on the new page is largely the same as the "About the Elastic Stack" section. Why not just replace the "About the Elastic Stack" text with the information on the new page? 

Or are we unable to do this because the new page includes a graphic? If so, then I agree with Nik's proposal.

2022-10-27 17:33 UTC, abdonpijpelink commented
@KOTungseth That's a good idea! This is what that would look like:

![stack in landing page](https://user-images.githubusercontent.com/9715543/198359030-ef0b359e-dda8-43ca-b850-471ac31faac0.gif)

If we want to go this route, I can submit a new PR for that. Note that because the landing page is not generated out of asciidoc, we'd have to author this section in HTML.

2022-10-27 20:49 UTC, KOTungseth commented
@abdonpijpelink that looks so good! If we can author this content in HTML, I say let's go for it.

2022-11-01 15:09 UTC, abdonpijpelink commented
Closing in favor of https://github.com/elastic/docs/pull/2557

2022-11-01 15:09 UTC, closed without merging