Update current version for .NET client docs
elastic/docs pull request #2660
Opened 2023-04-12 13:26 UTC by stevejgordon

We have now released 8.1.0 of the client and, therefore, should direct the current version in the docs to that branch.

2023-04-17 14:11 UTC, szabosteve requested changes
The `live` property should also be updated with `8.1`.

2023-04-17 14:11 UTC, szabosteve commented on conf.yaml
>                  live:       [ main, 8.0, 7.17, 7.16, 6.x, 5.x, 2.x, 1.x ]
Please add 8.1 to the live branches, too.

```suggestion
                live:       [ main, 8.1, 8.0, 7.17, 7.16, 6.x, 5.x, 2.x, 1.x ]
```

2023-04-17 17:38 UTC, stevejgordon commented
> The `live` property should also be updated with `8.1`.

Yes it should, thanks!!

2023-04-18 09:10 UTC, szabosteve approved these changes
LGTM!

2023-04-18 13:20 UTC, merged