Add help to code snippets widget
elastic/docs pull request #2867
Opened 2023-12-13 17:16 UTC by leemthompo

Adds an ℹ️ button to our docs code example widget, just before the gear icon:

<img width="500" alt="Screenshot 2023-12-13 at 18 10 45" src="https://github.com/elastic/docs/assets/32779855/7a0f7377-fe86-4a64-a94c-efd1bef262f7">

When clicked it raises an plaintext alert box that explains how to use our code examples: 

<img width="881" alt="Screenshot 2023-12-13 at 18 11 13" src="https://github.com/elastic/docs/assets/32779855/16d21621-0750-44fa-a5ca-016bf57cb27e">

## Problem

Lots of folks don't know how our code samples widget works. This attempts to provide help text, without switching context by linking to docs.

### Issues

This is a quick and dirty solution. We could use a more involved modal to enable rich text, but I was able to put this together in less than an hour.

2023-12-14 11:05 UTC, abdonpijpelink reviewed
This renders a little less beautiful for me (Chrome on MacOS).

2023-12-14 11:09 UTC, leemthompo commented
> This renders a little less beautiful for me (Chrome on MacOS).

Eugh 😅

2023-12-14 11:19 UTC, leemthompo commented
<img width="545" alt="Screenshot 2023-12-14 at 12 17 49" src="https://github.com/elastic/docs/assets/32779855/5c7a4956-e1e6-4a9c-bdf5-cd7a64299c20">

@abdonpijpelink while we're looking at this, shouldn't `curl host` and `curl username` read Elasticsearch host/username?

2023-12-14 11:37 UTC, leemthompo commented
<img width="454" alt="Screenshot 2023-12-14 at 12 34 15" src="https://github.com/elastic/docs/assets/32779855/a93c6a7a-964f-4524-8faf-cc43f35f8564">

@abdonpijpelink by simply cutting the text down and removing excessive newlines, we can get the dialog to open in Chrome without need to scroll

2023-12-14 11:53 UTC, leemthompo commented
I'm probably breaking every UI best practice under the sun here, but I feel like the current widget is broken for new users who don't understand it. Plus I don't know how to estimate the effort it would take to make this incrementally cleaner or whether it would be worth it...

2023-12-14 14:35 UTC, bmorelli25 requested changes
Hi Liam. I appreciate you opening this PR, but I have some concerns with these changes.

My main concern (and not your fault because I'm not sure how widely this was communicated) is that we're not supposed to push updates to the legacy doc build at this time. We have working migration scripts for the transition to Docsmobile, and every update to the legacy build system has the potential to break those scripts.

My secondary concern is that I just don't know how useful this update is. I don't see anything in the new descriptions that adds additional context to what this widget is and what it does. The updates just seem to just be describing the UI but with more words. As an example, the button name is `Copy as curl`. I don't think `Select "Copy as curl" to copy the code in curl format.` really adds anything useful.

If we need to change text, like changing "Enter the URL of the Console editor" to "Enter the URL of the Kibana Console editor" or changing "curl host" to "Elasticsearch host", I think that makes a lot more sense than trying to describe these buttons in an info pop up.

2023-12-14 14:55 UTC, leemthompo commented
Independent of this PR, the bigger picture question is "How do we help folks use our code samples?" given this widget is actually pretty confusing to new users.

2023-12-14 21:16 UTC, KOTungseth submitted a review, later dismissed
I made some tweaks. Thank you for creating this!

2023-12-14 21:16 UTC, KOTungseth commented on resources/web/docs_js/components/console_widget.jsx
> +    alert('1. Use the toggle in the lower left-hand corner to change client languages.\n' +
```suggestion
    alert('1. To change the client language, use the dropdown.\n' +
```

2023-12-14 21:16 UTC, KOTungseth commented on resources/web/docs_js/components/console_widget.jsx
> +          '2. - Select "Copy as curl" to copy the code in curl format.\n' +
```suggestion
          '2. To copy the code in curl format, click "Copy as curl".\n' +
```

2023-12-14 21:16 UTC, KOTungseth commented on resources/web/docs_js/components/console_widget.jsx
> +          '    - Select "View in Console" to load example in Kibana Console.\n' +
```suggestion
          '3. To open the example in Kibana Console:
                a. Click the gear icon (⚙) in the lower right-hand corner to configure your Elasticsearch host URL, username, and Kibana Console  URL. This ensures the code examples target your Elasticsearch instance.
                b. Click "View in Console".\n' +
```

2023-12-14 21:16 UTC, KOTungseth commented on resources/web/docs_js/components/console_widget.jsx
> +          '3. Use the gear icon (⚙) in the lower right-hand corner to configure your Elasticsearch host URL, username and Kibana Console URL.This ensures the code examples target your Elasticsearch i
```suggestion
```

2023-12-18 09:19 UTC, leemthompo commented
https://github.com/elastic/docs/pull/2867/commits/06c9eedcdead2f158eaa4aab1c5bbbc8447010b0 tightens up text and makes it clearer that whether using curl or console you need to first configure variables using the "⚙"

2023-12-18 22:39 UTC, chriscressman reviewed
I think the proposed UI is valuable in the following scenario: I click "Copy as curl" or "View in Console" and it doesn't work in some way. I see the information icon and click it to see if it helps me find a solution.

In this case, I suggest simpler text in the help dialog, something like:

> By default, "Copy as curl" and "View in Console" use localhost. Configure your Elasticsearch and Kibana locations using the gear icon (⚙).

Then, I would improve the labels in the config form:

> Kibana Console URL for "View in Console"
> Elasticsearch host for "Copy as curl"
> Elasticsearch username for "Copy as curl"

2023-12-19 08:52 UTC, leemthompo commented
> I think the proposed UI is valuable in the following scenario: I click "Copy as curl" or "View in Console" 

We also have to account for folks who don't know what Console is, and are just confused or assume it means terminal.

> Then, I would improve the labels in the config form:

Agree but this messes with tests, so I didn't pull on that thread

2023-12-20 18:23 UTC, closed without merging

2023-12-20 18:23 UTC, leemthompo commented
Closing as we're not supposed to push updates to the legacy doc build at this time